export const actionTypes = {
  FETCH: 'GAME/QUERY/FETCH',
  FETCH_SUCCESS: 'GAME/QUERY/FETCH_SUCCESS',
  FETCH_ERROR: 'GAME/QUERY/FETCH_ERROR',
  CANCEL: 'GAME/QUERY/CANCEL'
}

export const KEY = 'gameQuery'
